fix: destroy 워크 스페이스 설정 수정
- env 설정 전 env 값을 참조하던 문제 수정

diff --git a/.github/workflows/deploy-lxd.yaml b/.github/workflows/deploy-lxd.yaml
--- a/.github/workflows/deploy-lxd.yaml
+++ b/.github/workflows/deploy-lxd.yaml
@@ -58,6 +58,9 @@ jobs:
           elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
             echo "ENV=dev" >> $GITHUB_ENV
             echo "WORKSPACE_NAME=bannote-server-dev" >> $GITHUB_ENV
+          else
+            echo "Error: Deploy workflow must be run from 'main' or 'dev' branch."
+            exit 1
           fi
 
       - name: Terraform Apply
